---
# Configure NGINX
- name: Create default nginx directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop: "{{ nginx_dir }}"
- name: Create data directories for sites
  file:
    path: "/var/www/{{ data_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
- name: Remove default conf and directories
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ nginx_default }}"
  notify: Reload nginx
- name: Configure nginx.conf
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_conf }}"
    group: root
    owner: root
    mode: 0644
  notify: Reload nginx
- name: Configure sites-enabled (vhosts)
  template:
    src: "example.conf.j2"
    dest: "/etc/nginx/sites-available/example.conf"
    group: root
    owner: root
    mode: 0644
  notify: Reload nginx
- name: Symlink sites-available to sites-enabled
  file:
    src: "/etc/nginx/sites-available/example.conf"
    dest: "/etc/nginx/sites-enabled/example.conf"
    state: link
  notify: Reload nginx
